---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  releaseName: bazarr
  interval: 10m
  chart:
    # renovate: registryUrl=https://k8s-at-home.com/charts/
    spec:
      chart: bazarr
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v1.0.3
    env:
      TZ: ${TIMEZONE}
      PUID: 816
      PGID: 816
    podSecurityContext:
      runAsUser: 816
      runAsGroup: 816
      fsGroup: 816
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 816
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
      media:
        enabled: true
        existingClaim: media-nfs-media-pvc
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "subtitles"
          hajimari.io/appName: "bazarr"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "bazarr.${SECRET_DOMAIN}"
            secretName: bazarr-cert
    resources:
      requests:
        cpu: 15m
        memory: 200M
      limits:
        cpu: 250m
        memory: 500M
