# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:leh0SjjaH590XjIRlDxU1hRc0ydMN3uF4Q==,iv:Yx9UhTFyQAWLL3THCYYon3TT7bFKBSUy+6q4mUBvSDs=,tag:4I92ZmrOoty+CciopVj78Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:63QHn4Pjt2XvGth46s1ngo/v83LM/duvFbrc/CdQaYX/YkxUqA==,iv:Co331AljgUVH8s+CH9ObprIscaeY8T6vSRyKNIHuZwE=,tag:PJ+lJXoVyQZnfHVpMKLJlg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:OdagiW50+E/5Q8XlDomoYUg=,iv:oh2HOKWTkLsWBOsJakz9NvYNBtfiWOPUnBMxJxOOdyA=,tag:XvhyH3AUY2ItAV9+feAGOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1naq2upd4pgt5w4ja55py00cycptx0xmt7mqy0hrusayaa09sq5lskkdtg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYjV1VkpJZVNpQUp6Yy94
            Z29PVFZqNWJuQmJxYnRxVzBIRnRTU21ORVU4Cmo1WnRjU1BkSkNvdlFza25LVzZZ
            VmhSR3ovRlVtNGFOdU52MmNLVFZUZjQKLS0tIFM2ODJDNjZvODBjaXp4akR4ZGxI
            SGIxQmJMbkUrajBEZ0xuN2R0NGRZVDQKj9OoOilUw6mKWprt6amemag0sJggRpwx
            ll5k9LCty7NxKQBGKQTFH7TVQwcTIAVvPsJBoujGBBZdv0BHh5LduA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-27T21:22:07Z"
    mac: ENC[AES256_GCM,data:uarTx9jbu0I0woE9TfraBad775X2W+51LONFdqBESj6Jl4sVUcesF3cvIPl4ATRn0eNgge+Ay+fFjapZzpdz7VUuSGWuQNMNh+zPMwoH8dqzoy4gpN2z28xaH9jkZke6ck+YfZOh3H9Ej0iUIIp1gWfas/cbA7/uaZ+AkJ7qJt8=,iv:Owo/WuT3vNyudhXSTjOKHNrVsVEr803KPp2jCgw2uUo=,tag:M4tyyeXrqHWhqWdsY4SvpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
