---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex-server
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`plex.${SECRET_OLD_DOMAIN}`)
      services:
        - kind: Service
          name: plex-server
          port: 32400
  tls:
    secretName: plex-server-cert
