---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: networking-rfc1918-ips@kubernetescrd
      - name: networking-chain-no-auth@kubernetescrd
