# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:QDVm92Sn7vNJxJDSShM5FIjVa61BwgUgwFOyPbAXrMXm4s6ehQ==,iv:O8A8O/INs4+Vhdkz1PvJBZ6kKLXpxLT8YBYKuB/Qww4=,tag:5isjWHFN8X0jzGAKf5/Wiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1naq2upd4pgt5w4ja55py00cycptx0xmt7mqy0hrusayaa09sq5lskkdtg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU2pOcjQ0UndlMUdNenVk
            Y1EzbHI4dFZPakVCeW1rRkdXcjNuSzdvTnlNCkJDWGU2aUN2SE5JZmh1eWYwUXRE
            RHZVOEFJbDhjNmJrRlB0RFozNGJxcTgKLS0tIDg5ZW9tdDFobzJoTFZEcTRxeGhu
            ZERwWjkrNXBER3g3eEQ0cmNzTElQK2sKSC5AfrPEu9Ux7HOTJSPvI+AD0+EusFd5
            TtiSU2j0WleQb10qf5fagdSIRYT1ILxjr9mUkXNnniONlCrl5tImGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-27T21:22:07Z"
    mac: ENC[AES256_GCM,data:FbIHj+2YjGEqq3NTs0viIftlXZ+zIbiH0ffq3InhhGO/Xc6E7njTGhWkwZw0+V232oPq2VFv6EvbwU78Z0pThpDValPexWfnIxO3mjKrBId8aT3rb33jrr8leBxpGANvw57WdctV3bYughsHaLhvV9dfw4A5pLRd23M8VhFogCo=,iv:C/j45i/TqQac4crGVjUf65xkTJLtzl4ANS6E3cBC5GM=,tag:djMSelTimpKwXWT7f87EIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
